using Microsoft.EntityFrameworkCore;

namespace AtlasCRM.Infrastructure.Persistence;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(AtlasCrmDbContext dbContext)
    {
        await dbContext.Database.EnsureCreatedAsync();
        await EnsureRuntimeSchemaAsync(dbContext);
        await EnsureDataMigrationsAsync(dbContext);
    }

    /// <summary>
    /// Migrações de dados executadas uma única vez (controladas por schema_migrations).
    /// Idempotente: não roda de novo após aplicada, preservando alterações manuais.
    /// </summary>
    public static async Task EnsureDataMigrationsAsync(AtlasCrmDbContext dbContext)
    {
        // Backfill do funil de 7 etapas a partir do LeadStatus legado.
        // Mapa aprovado: New->Mapeado | Contacted/MessageSent/FollowUp->Prospectado |
        // Qualified->Respondeu | MeetingScheduled->Reunião agendada |
        // InNegotiation->Reunião feita | Converted->Fechado(Ganho) | Lost->Perdido.
        await dbContext.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE name = 'leads_funnel_stage_backfill') THEN
                    UPDATE leads SET
                        funnel_stage = CASE status
                            WHEN 1 THEN 1   -- New          -> Mapeado
                            WHEN 2 THEN 2   -- Contacted     -> Prospectado
                            WHEN 6 THEN 2   -- MessageSent   -> Prospectado
                            WHEN 7 THEN 2   -- FollowUp      -> Prospectado
                            WHEN 3 THEN 3   -- Qualified     -> Respondeu
                            WHEN 9 THEN 4   -- MeetingScheduled -> Reunião agendada
                            WHEN 8 THEN 5   -- InNegotiation -> Reunião feita
                            WHEN 5 THEN 7   -- Converted     -> Fechado
                            WHEN 4 THEN 7   -- Lost          -> Perdido
                            ELSE 1
                        END,
                        outcome = CASE status
                            WHEN 5 THEN 1   -- Converted -> Ganho
                            WHEN 4 THEN 2   -- Lost      -> Perdido
                            ELSE 0
                        END;
                    INSERT INTO schema_migrations (name) VALUES ('leads_funnel_stage_backfill');
                END IF;
            END $$;
            """);
    }

    public static async Task EnsureRuntimeSchemaAsync(AtlasCrmDbContext dbContext)
    {
        await dbContext.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                title VARCHAR(180) NOT NULL,
                description TEXT NULL,
                type INTEGER NOT NULL,
                url TEXT NULL,
                stored_file_name VARCHAR(260) NULL,
                original_file_name VARCHAR(260) NULL,
                content_type VARCHAR(120) NULL,
                size_bytes BIGINT NULL,
                created_at_utc TIMESTAMPTZ NOT NULL,
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE INDEX IF NOT EXISTS ix_documents_company_id ON documents (company_id);
            CREATE INDEX IF NOT EXISTS ix_documents_company_type ON documents (company_id, type);
            ALTER TABLE documents ADD COLUMN IF NOT EXISTS sector VARCHAR(60) NULL;
            ALTER TABLE documents ADD COLUMN IF NOT EXISTS tags_json TEXT NULL;
            ALTER TABLE documents ADD COLUMN IF NOT EXISTS is_onboarding BOOLEAN NOT NULL DEFAULT FALSE;
            ALTER TABLE documents ADD COLUMN IF NOT EXISTS visibility VARCHAR(20) NOT NULL DEFAULT 'private';

            ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_temperature INTEGER NOT NULL DEFAULT 2;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_score INTEGER NOT NULL DEFAULT 0;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_notes VARCHAR(500) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS extra_data_json TEXT NULL;
            CREATE INDEX IF NOT EXISTS ix_leads_company_qualification_temperature ON leads (company_id, qualification_temperature);

            -- Processo comercial Atlas: funil de 7 etapas + campos do lead
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS funnel_stage INTEGER NOT NULL DEFAULT 1;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS outcome INTEGER NOT NULL DEFAULT 0;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS channel VARCHAR(40) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS company_name VARCHAR(180) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS contact_handle VARCHAR(140) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_contact_at_utc TIMESTAMPTZ NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_follow_up_at_utc TIMESTAMPTZ NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS observations VARCHAR(2000) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS proposal_value NUMERIC(18,2) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS contract_value NUMERIC(18,2) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS loss_reason INTEGER NOT NULL DEFAULT 0;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS is_cold BOOLEAN NOT NULL DEFAULT FALSE;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS follow_up_step INTEGER NOT NULL DEFAULT 0;
            CREATE INDEX IF NOT EXISTS ix_leads_company_funnel_stage ON leads (company_id, funnel_stage);
            CREATE INDEX IF NOT EXISTS ix_leads_company_next_follow_up_at_utc ON leads (company_id, next_follow_up_at_utc);

            -- Controle de migrações de dados executadas uma única vez
            CREATE TABLE IF NOT EXISTS schema_migrations (
                name VARCHAR(120) PRIMARY KEY,
                applied_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS user_permissions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                permission VARCHAR(80) NOT NULL,
                created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_permissions_company_user_permission
                ON user_permissions (company_id, user_id, permission);
            
            CREATE TABLE IF NOT EXISTS finance_entries (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                occurred_at_utc TIMESTAMPTZ NOT NULL,
                type VARCHAR(16) NOT NULL,
                category VARCHAR(120) NOT NULL,
                amount NUMERIC(18,2) NOT NULL,
                currency VARCHAR(10) NOT NULL,
                notes TEXT NULL,
                attachment_file_name VARCHAR(260) NULL,
                created_at_utc TIMESTAMPTZ NOT NULL,
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE INDEX IF NOT EXISTS ix_finance_entries_company_id ON finance_entries (company_id);
            ALTER TABLE finance_entries ADD COLUMN IF NOT EXISTS source_lead_id BIGINT NULL REFERENCES leads(id) ON DELETE SET NULL;
            CREATE INDEX IF NOT EXISTS ix_finance_entries_company_occurred_at_utc ON finance_entries (company_id, occurred_at_utc);

            CREATE TABLE IF NOT EXISTS appointments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                title VARCHAR(200) NOT NULL,
                description VARCHAR(1000) NULL,
                start_at_utc TIMESTAMPTZ NOT NULL,
                end_at_utc TIMESTAMPTZ NOT NULL,
                type INTEGER NOT NULL DEFAULT 2,
                status INTEGER NOT NULL DEFAULT 1,
                lead_id BIGINT NULL REFERENCES leads(id) ON DELETE SET NULL,
                deal_id BIGINT NULL REFERENCES deals(id) ON DELETE SET NULL,
                assigned_user_id BIGINT NOT NULL REFERENCES users(id),
                created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE INDEX IF NOT EXISTS ix_appointments_company_id ON appointments (company_id);
            CREATE INDEX IF NOT EXISTS ix_appointments_company_start ON appointments (company_id, start_at_utc);
            CREATE INDEX IF NOT EXISTS ix_appointments_company_status ON appointments (company_id, status);

            CREATE TABLE IF NOT EXISTS custom_field_definitions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                target INTEGER NOT NULL DEFAULT 1,
                name VARCHAR(120) NOT NULL,
                field_key VARCHAR(140) NOT NULL,
                type INTEGER NOT NULL DEFAULT 1,
                options_json TEXT NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE INDEX IF NOT EXISTS ix_custom_field_definitions_company_target
                ON custom_field_definitions (company_id, target);
            CREATE UNIQUE INDEX IF NOT EXISTS ix_custom_field_definitions_company_target_field_key
                ON custom_field_definitions (company_id, target, field_key);

            CREATE TABLE IF NOT EXISTS whatsapp_conversations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                contact_phone VARCHAR(40) NOT NULL,
                contact_name VARCHAR(140) NOT NULL,
                lead_id BIGINT NULL REFERENCES leads(id) ON DELETE SET NULL,
                last_message_preview VARCHAR(160) NULL,
                last_message_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                unread_count INTEGER NOT NULL DEFAULT 0,
                created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_whatsapp_conversations_company_contact_phone
                ON whatsapp_conversations (company_id, contact_phone);
            CREATE INDEX IF NOT EXISTS ix_whatsapp_conversations_company_last_message_at_utc
                ON whatsapp_conversations (company_id, last_message_at_utc);

            CREATE TABLE IF NOT EXISTS whatsapp_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                conversation_id BIGINT NOT NULL REFERENCES whatsapp_conversations(id) ON DELETE CASCADE,
                is_inbound BOOLEAN NOT NULL DEFAULT TRUE,
                text VARCHAR(4000) NOT NULL,
                sent_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                sender_name VARCHAR(140) NULL,
                created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE INDEX IF NOT EXISTS ix_whatsapp_messages_conversation_sent_at_utc
                ON whatsapp_messages (conversation_id, sent_at_utc);
            """);
    }
}
