using Microsoft.EntityFrameworkCore;

namespace AtlasCRM.Infrastructure.Persistence;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(AtlasCrmDbContext dbContext)
    {
        await dbContext.Database.EnsureCreatedAsync();
        await EnsureRuntimeSchemaAsync(dbContext);
    }

    public static async Task EnsureRuntimeSchemaAsync(AtlasCrmDbContext dbContext)
    {
        await dbContext.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id BIGINT NOT NULL REFERENCES companies(id),
                title VARCHAR(180) NOT NULL,
                description TEXT NULL,
                type INTEGER NOT NULL,
                url TEXT NULL,
                stored_file_name VARCHAR(260) NULL,
                original_file_name VARCHAR(260) NULL,
                content_type VARCHAR(120) NULL,
                size_bytes BIGINT NULL,
                created_at_utc TIMESTAMPTZ NOT NULL,
                updated_at_utc TIMESTAMPTZ NULL
            );
            CREATE INDEX IF NOT EXISTS ix_documents_company_id ON documents (company_id);
            CREATE INDEX IF NOT EXISTS ix_documents_company_type ON documents (company_id, type);

            ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_temperature INTEGER NOT NULL DEFAULT 2;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_score INTEGER NOT NULL DEFAULT 0;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_notes VARCHAR(500) NULL;
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS extra_data_json TEXT NULL;
            CREATE INDEX IF NOT EXISTS ix_leads_company_qualification_temperature ON leads (company_id, qualification_temperature);
            """);
    }
}
