CREATE TABLE IF NOT EXISTS whatsapp_integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    provider INTEGER NOT NULL,
    instance_name VARCHAR(120) NOT NULL,
    phone_number VARCHAR(40) NOT NULL,
    webhook_url TEXT NULL,
    api_base_url TEXT NULL,
    api_token TEXT NULL,
    capture_leads_enabled BOOLEAN NOT NULL,
    broadcast_enabled BOOLEAN NOT NULL,
    status INTEGER NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_whatsapp_integrations_company_id ON whatsapp_integrations (company_id);

INSERT INTO whatsapp_integrations (id, company_id, provider, instance_name, phone_number, webhook_url, api_base_url, api_token, capture_leads_enabled, broadcast_enabled, status, created_at_utc, updated_at_utc)
VALUES
    (1, 1, 1, 'atlas-demo', '+55 11 99999-8888', 'https://example.com/whatsapp/webhook', 'https://api.exemplo-whatsapp.com', 'demo-token', TRUE, TRUE, 2, '2026-04-06T00:00:00Z', NULL)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('whatsapp_integrations', 'id'), COALESCE((SELECT MAX(id) FROM whatsapp_integrations), 1), TRUE);
